---
- name: Get GitOps info from PackageManifest
  k8s_info:
    api_version: packages.operators.coreos.com/v1
    kind: PackageManifest
    name: openshift-gitops-operator
    namespace: openshift-operators
  register: acm_object

- name: Set defaultChannel and catalogSource
  set_fact:
    operator_channel: "{{ acm_object.resources | json_query('[0].status.defaultChannel') }}"
    catalog_source: "{{ acm_object.resources | json_query('[0].status.catalogSource') }}"

- name: Create GitOps subscription
  k8s:
    state: present
    template: "00_Subscription.yaml.j2"
    wait: true

- name: Check GitOps Operator (presence of deployments -> timeout ~20 mins)
  k8s:
    api_version: apps/v1
    kind: Deployment
    name: "{{ item }}"
    namespace: openshift-gitops
    state: present
    wait: true
    wait_timeout: 120
  loop:
    - openshift-gitops-redis
    - openshift-gitops-server
    - openshift-gitops-repo-server
    - openshift-gitops-dex-server
    - openshift-gitops-applicationset-controller
  register: gitops_deploy
  retries: 10
  delay: 30
  until: gitops_deploy is not failed
